AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
    - '**/gem_rake_helper.rb'
  Exclude:
    - 'script/**/*'
    - 'vendor/**/*'
    - '**/tmp/**/*'
    - '**/bin/**/*'
    - 'middleman-core/lib/middleman-core/step_definitions/**/*'
    - 'middleman-core/fixtures/**/*'
    - 'middleman-core/features/**/*'
    - 'middleman-core/spec/**/*'
    - 'middleman-cli/lib/middleman-cli/templates/**/*'
    - 'middleman-cli/fixtures/**/*'
    - 'middleman-cli/features/**/*'
    - 'middleman-cli/spec/**/*'
DoubleNegation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
HashSyntax:
  EnforcedStyle: ruby19
SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
PerlBackrefs:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
AssignmentInCondition:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
SuppressedException:
  Enabled: false
EndAlignment:
  EnforcedStyleAlignWith: variable
SignalException:
  Enabled: false
RegexpLiteral:
  Enabled: false
FormatString:
  Enabled: false
CaseIndentation:
  EnforcedStyle: end
TrivialAccessors:
  Enabled: false
SingleLineBlockParams:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/BeginEndAlignment: # (new in 0.91)
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor: # (new in 0.83)
  Enabled: false
Layout/SpaceAroundMethodCallOperator: # (new in 0.82)
  Enabled: false
Lint/BinaryOperatorWithIdenticalOperands: # (new in 0.89)
  Enabled: false
Lint/ConstantDefinitionInBlock: # (new in 0.91)
  Enabled: false
Lint/DeprecatedOpenSSLConstant: # (new in 0.84)
  Enabled: false
Lint/DuplicateElsifCondition: # (new in 0.88)
  Enabled: false
Lint/DuplicateRequire: # (new in 0.90)
  Enabled: false
Lint/DuplicateRescueException: # (new in 0.89)
  Enabled: false
Lint/EmptyConditionalBody: # (new in 0.89)
  Enabled: false
Lint/EmptyFile: # (new in 0.90)
  Enabled: false
Lint/FloatComparison: # (new in 0.89)
  Enabled: false
Lint/HashCompareByIdentity: # (new in 0.93)
  Enabled: false
Lint/IdentityComparison: # (new in 0.91)
  Enabled: false
Lint/MissingSuper: # (new in 0.89)
  Enabled: false
Lint/MixedRegexpCaptureTypes: # (new in 0.85)
  Enabled: false
Lint/OutOfRangeRegexpRef: # (new in 0.89)
  Enabled: false
Lint/RaiseException: # (new in 0.81)
  Enabled: false
Lint/RedundantSafeNavigation: # (new in 0.93)
  Enabled: false
Lint/SelfAssignment: # (new in 0.89)
  Enabled: false
Lint/StructNewOverride: # (new in 0.81)
  Enabled: false
Lint/TopLevelReturnWithArgument: # (new in 0.89)
  Enabled: false
Lint/TrailingCommaInAttributeDeclaration: # (new in 0.90)
  Enabled: false
Lint/UnreachableLoop: # (new in 0.89)
  Enabled: false
Lint/UselessMethodDefinition: # (new in 0.90)
  Enabled: false
Lint/UselessTimes: # (new in 0.91)
  Enabled: false
Style/AccessorGrouping: # (new in 0.87)
  Enabled: false
Style/BisectedAttrAccessor: # (new in 0.87)
  Enabled: false
Style/CaseLikeIf: # (new in 0.88)
  Enabled: false
Style/ClassEqualityComparison: # (new in 0.93)
  Enabled: false
Style/CombinableLoops: # (new in 0.90)
  Enabled: false
Style/ExplicitBlockArgument: # (new in 0.89)
  Enabled: false
Style/ExponentialNotation: # (new in 0.82)
  Enabled: false
Style/GlobalStdStream: # (new in 0.89)
  Enabled: false
Style/HashAsLastArrayItem: # (new in 0.88)
  Enabled: false
Style/HashEachMethods: # (new in 0.80)
  Enabled: false
Style/HashLikeCase: # (new in 0.88)
  Enabled: false
Style/HashTransformKeys: # (new in 0.80)
  Enabled: false
Style/HashTransformValues: # (new in 0.80)
  Enabled: false
Style/KeywordParametersOrder: # (new in 0.90)
  Enabled: false
Style/OptionalBooleanParameter: # (new in 0.89)
  Enabled: false
Style/RedundantAssignment: # (new in 0.87)
  Enabled: false
Style/RedundantFetchBlock: # (new in 0.86)
  Enabled: false
Style/RedundantFileExtensionInRequire: # (new in 0.88)
  Enabled: false
Style/RedundantRegexpCharacterClass: # (new in 0.85)
  Enabled: false
Style/RedundantRegexpEscape: # (new in 0.85)
  Enabled: false
Style/RedundantSelfAssignment: # (new in 0.90)
  Enabled: false
Style/SingleArgumentDig: # (new in 0.89)
  Enabled: false
Style/SlicingWithRange: # (new in 0.83)
  Enabled: false
Style/SoleNestedConditional: # (new in 0.89)
  Enabled: false
Style/StringConcatenation: # (new in 0.89)
  Enabled: false
Layout/EndOfLine:
  Enabled: false